server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: '@eogks5171'

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 623893011817-4oq274ahtck95ct1llv4aqqnln3e9sj8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 763923828732109
            client-secret: 30eb140f844b5bf473a13d0dd348375f
            scope:
              - email
              - public_profile

          naver:
            client-id: NRmUk33r8tfUZ2CAtMj7
            client-secret: h3hGV5zHVY
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: 7b8954aeef8a543f6db2c9aadfa30d18
            client-secret: piLB5GCbRGiV9cgMB7PG6ZGI09r0EPmV
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ????? json? response ???? ????.

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # ????? json? id ???? ????.

